### ISSUE TITLE
Support the new Rest API v8

### ISSUE THREAD

**Issue by garyking** [h6y3/todoist-ruby#1]
Is there any chance that you will support the new [Todoist v8 Rest API](https://developer.todoist.com/rest/v8/) with this library?

Thanks!

**Comment by h6y3** [comment]
I will work on it.  I have not reviewed the v8 library extensively but I use this library myself.

**Comment by h6y3** [comment]
So after having taken a look at this, it seems the sync API is more powerful.  Given that v8 is a rest API, it doesn't seem like a library is needed since a simple REST library should do the trick for most people.
