### ISSUE TITLE
v8 -> v9 transition

### ISSUE THREAD

**Issue by sergueif** [h6y3/todoist-ruby#14]
Hello, I'm getting occasional 404s like `"This API endpoint is no longer available.\n\nPlease refer to our documentation to upgrade your client to use the latest API version: https://developer.todoist.com/sync/v9/#migrating-from-v8\n\n"`

I don't know how tricky will it be to comprehensively update the gem for the v9 of sync api, but in the meantime, any workaround suggestions? How could I try to just tweak the version in the base url and hope that the few endpoints I actually use, maybe things just stay the same and I can keep using this gem?

**Comment by h6y3** [comment]
I will take a look at this over the next couple of weeks. Sorry for not seeing this earlier. 

If you'd like to take a crack at this it should be easy to debug once we run the unit tests. Just send a pull request. 

In the past it was as simple as changing the url scheme from v8 to v9 as generally the endpoints have taken the same arguments.

**Comment by h6y3** [comment]
@sergueif I've completed the changes and all seems to be okay (at least as far as testing from my side using test accounts).  I will need to add this to some of my projects to verify that this works from the perspective of using the gem from rubygems, etc. but you might want to give it a shot and see how far you get.

**Comment by sergueif** [comment]
oh wow, thank you for this update. I'll try it as soon as I can!

**Comment by h6y3** [comment]
One thing I will say is that with each release there are countless changes Todoist makes in terms of data types returned in their API.  The library's interface generally uses hashes to pass around variables so luckily the core interfaces are stable, however, the downside is that while you might not need to change a lot of code, you might find things breaking.

The unit tests do a good amount of coverage and I catch a lot of these changes in the tests and change my tests to show how things change from version to version, but there are many more changes than my tests can account for.

I just discovered for example that booleans are now represented by actual booleans whereas before the API was returning 0 or 1.
